import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const cooperHewitt = localFont({
  src: [
    {
      path: "./fonts/cooper-hewitt-latin-100-normal.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/cooper-hewitt-latin-200-normal.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/cooper-hewitt-latin-300-normal.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/cooper-hewitt-latin-400-normal.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/cooper-hewitt-latin-500-normal.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/cooper-hewitt-latin-600-normal.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/cooper-hewitt-latin-700-normal.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/cooper-hewitt-latin-800-normal.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-cooper-hewitt",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cooperHewitt.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
