export const galleryImages = [
  {
    src: '/images/gallery/nixos.png',
    alt: 'NixOS Setup',
    title: 'NixOS',
    description: 'My daily driver Linux distro',
    span: 'col-span-2 row-span-2',
    category: 'Desktop',
  },
  {
    src: '/images/gallery/btop.png',
    alt: 'Btop System Monitor',
    title: 'Btop++',
    description: 'Terminal system monitor',
    span: 'col-span-1 row-span-1',
    category: 'Terminal',
  },
  {
    src: '/images/gallery/arasaka-parade.png',
    alt: 'Arasaka Parade',
    title: 'Arasaka Parade',
    description: 'Cyberpunk Parade of Arasaka photo',
    span: 'col-span-1 row-span-2',
    category: 'Wallpaper',
  },
  {
    src: '/images/gallery/zeneistu.png',
    alt: 'Zeneistu Anime Artwork',
    title: 'Zeneistu',
    description: 'Anime inspired art of Zeneistu',
    span: 'col-span-2 row-span-1',
    category: 'Art',
  },
  {
    src: '/images/gallery/blacksphere.png',
    alt: 'Black_Sapphire_Artwork',
    title: 'Black Sapphire',
    description: 'Cyberpunk photo of Black Sapphire',
    span: 'col-span-4 row-span-2',
    category: 'Art',
  },
]
